sources:
  - Crispy.glyphs
familyName: Crispy
buildStatic: false

spacingAxis:
  min: 0
  max: 50

fvarInstances:
  Crispy[SPAC,XOPQ,XTRA,YOPQ].ttf:
  - name: ExtraLight
    coordinates:
      wght: 200
      wdth: 100
      opsz: 12
  - name: Light
    coordinates:
      wght: 300
      wdth: 100
      opsz: 12
  - name: Regular
    coordinates:
      wght: 400
      wdth: 100
      opsz: 12
  - name: Medium
    coordinates:
      wght: 500
      wdth: 100
      opsz: 12
  - name: SemiBold
    coordinates:
      wght: 600
      wdth: 100
      opsz: 12
  - name: Bold
    coordinates:
      wght: 700
      wdth: 100
      opsz: 12
  - name: ExtraBold
    coordinates:
      wght: 800
      wdth: 100
      opsz: 12
  - name: Black
    coordinates:
      wght: 900
      wdth: 100
      opsz: 12

avar2:
  Crispy[SPAC,XOPQ,XTRA,YOPQ].ttf:
  - in:
      wght: 200
      wdth: 100
      opsz: 72
    out:
      XTRA: 580
      XOPQ: 78.575
      YOPQ: 72.59
      SPAC: 0
  - in:
      wght: 300
      wdth: 100
      opsz: 72
    out:
      XTRA: 603.55
      XOPQ: 133.124
      YOPQ: 104.253
      SPAC: 0
  - in:
      wght: 400
      wdth: 100
      opsz: 72
    out:
      XTRA: 627
      XOPQ: 187.672
      YOPQ: 135.916
      SPAC: 0
  - in:
      wght: 500
      wdth: 100
      opsz: 72
    out:
      XTRA: 650.5
      XOPQ: 242.221
      YOPQ: 167.58
      SPAC: 0
  - in:
      wght: 600
      wdth: 100
      opsz: 72
    out:
      XTRA: 693.05
      XOPQ: 321.48
      YOPQ: 223.027
      SPAC: 0
  - in:
      wght: 700
      wdth: 100
      opsz: 72
    out:
      XTRA: 735.6
      XOPQ: 400.738
      YOPQ: 278.474
      SPAC: 0
  - in:
      wght: 800
      wdth: 100
      opsz: 72
    out:
      XTRA: 770
      XOPQ: 466.573
      YOPQ: 308.783
      SPAC: 0
  - in:
      wght: 900
      wdth: 100
      opsz: 72
    out:
      XTRA: 804.4
      XOPQ: 532.409
      YOPQ: 339.093
      SPAC: 0

  - in:
      wght: 200
      wdth: 100
      opsz: 12
    out:
      XTRA: 580
      XOPQ: 88.178594
      YOPQ: 90.7375
      SPAC: 50
  - in:
      wght: 300
      wdth: 100
      opsz: 12
    out:
      XTRA: 603.55
      XOPQ: 149.394681
      YOPQ: 130.31625
      SPAC: 50
  - in:
      wght: 400
      wdth: 100
      opsz: 12
    out:
      XTRA: 627
      XOPQ: 210.609647
      YOPQ: 169.895
      SPAC: 50
  - in:
      wght: 500
      wdth: 100
      opsz: 12
    out:
      XTRA: 650.5
      XOPQ: 271.825735
      YOPQ: 209.475
      SPAC: 50
  - in:
      wght: 600
      wdth: 100
      opsz: 12
    out:
      XTRA: 693.05
      XOPQ: 360.771929
      YOPQ: 278.78375
      SPAC: 50
  - in:
      wght: 700
      wdth: 100
      opsz: 12
    out:
      XTRA: 735.6
      XOPQ: 449.717
      YOPQ: 309.10614
      SPAC: 50
  - in:
      wght: 800
      wdth: 100
      opsz: 12
    out:
      XTRA: 770
      XOPQ: 523.598485
      YOPQ: 342.74913
      SPAC: 50
  - in:
      wght: 900
      wdth: 100
      opsz: 12
    out:
      XTRA: 804.4
      XOPQ: 597.481093
      YOPQ: 376.39323
      SPAC: 50


includeSourceFixes: false