sources:
- Crispy.glyphs
familyName: Crispy
buildStatic: true
spacingAxis:
  min: -20
  max: 40
fvarInstances:
  Crispy[SPAC,XOPQ,XTRA,YOPQ].ttf:
  - name: Thin
    coordinates:
      opsz: 48
      wdth: 100
      wght: 100
  - name: ExtraLight
    coordinates:
      opsz: 48
      wdth: 100
      wght: 200
  - name: Light
    coordinates:
      opsz: 48
      wdth: 100
      wght: 300
  - name: Regular
    coordinates:
      opsz: 48
      wdth: 100
      wght: 400
  - name: Medium
    coordinates:
      opsz: 48
      wdth: 100
      wght: 500
  - name: SemiBold
    coordinates:
      opsz: 48
      wdth: 100
      wght: 600
  - name: Bold
    coordinates:
      opsz: 48
      wdth: 100
      wght: 700

stat:
  Crispy[SPAC,XOPQ,XTRA,YOPQ].ttf:
  - name: Optical Size
    tag: opsz
    values:
    - name: 12pt
      value: 12
    - name: 48pt
      value: 48
    - name: 72pt
      value: 72
  - name: Width
    tag: wdth
    values:
    - name: '52'
      value: 52
    - name: Normal
      value: 100
    - name: '182'
      value: 182
    - name: '300'
      value: 300
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 100
    - name: ExtraLight
      value: 200
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700

avar2:
  Crispy[SPAC,XOPQ,XTRA,YOPQ].ttf:

  # =========================
  # Width = 52
  # =========================

  # OPSZ = 72

  # Thin Condensed-MaxOPSZ
  - in:
      opsz: 72
      wdth: 52
      wght: 100
    out:
      XTRA: 181.2
      XOPQ: 38.285
      YOPQ: 39.235
      SPAC: -20

  # OPSZ = 48

  # Thin Condensed
  - in:
      opsz: 48
      wdth: 52
      wght: 100
    out:
      XTRA: 181.2
      XOPQ: 40.3
      YOPQ: 41.3
      SPAC: 25

  # OPSZ = 12

  # Thin Condensed-MinOPSZ
  - in:
      opsz: 12
      wdth: 52
      wght: 100
    out:
      XTRA: 190.26
      XOPQ: 42.315
      YOPQ: 43.365
      SPAC: 20

  # OPSZ = 72

  # ExtraLight Condensed-MaxOPSZ
  - in:
      opsz: 72
      wdth: 52
      wght: 200
    out:
      XTRA: 248
      XOPQ: 74.1
      YOPQ: 80.75
      SPAC: -20

  # OPSZ = 48

  # ExtraLight Condensed
  - in:
      opsz: 48
      wdth: 52
      wght: 200
    out:
      XTRA: 248
      XOPQ: 78
      YOPQ: 85
      SPAC: 25

  # OPSZ = 12

  # ExtraLight Condensed-MinOPSZ
  - in:
      opsz: 12
      wdth: 52
      wght: 200
    out:
      XTRA: 260.4
      XOPQ: 81.9
      YOPQ: 89.25
      SPAC: 20

  # OPSZ = 72

  # Light Condensed-MaxOPSZ
  - in:
      opsz: 72
      wdth: 52
      wght: 300
    out:
      XTRA: 280
      XOPQ: 92.625
      YOPQ: 87.75
      SPAC: -20

  # OPSZ = 48

  # Light Condensed
  - in:
      opsz: 48
      wdth: 52
      wght: 300
    out:
      XTRA: 280
      XOPQ: 95
      YOPQ: 90
      SPAC: 25

  # OPSZ = 12

  # Light Condensed-MinOPSZ
  - in:
      opsz: 12
      wdth: 52
      wght: 300
    out:
      XTRA: 294
      XOPQ: 97.375
      YOPQ: 92.25
      SPAC: 20

  # OPSZ = 72

  # Regular Condensed-MaxOPSZ
  - in:
      opsz: 72
      wdth: 52
      wght: 400
    out:
      XTRA: 290
      XOPQ: 147
      YOPQ: 130
      SPAC: -20

  # OPSZ = 48

  # Regular Condensed
  - in:
      opsz: 48
      wdth: 52
      wght: 400
    out:
      XTRA: 290
      XOPQ: 147
      YOPQ: 130
      SPAC: 25

  # OPSZ = 12

  # Regular Condensed-MinOPSZ
  - in:
      opsz: 12
      wdth: 52
      wght: 400
    out:
      XTRA: 304.5
      XOPQ: 147
      YOPQ: 130
      SPAC: 20

  # OPSZ = 72

  # Medium Condensed-MaxOPSZ
  - in:
      opsz: 72
      wdth: 52
      wght: 500
    out:
      XTRA: 345
      XOPQ: 244
      YOPQ: 244
      SPAC: -20

  # OPSZ = 48

  # Medium Condensed
  - in:
      opsz: 48
      wdth: 52
      wght: 500
    out:
      XTRA: 345
      XOPQ: 240
      YOPQ: 240
      SPAC: 25

  # OPSZ = 12

  # Medium Condensed-MinOPSZ
  - in:
      opsz: 12
      wdth: 52
      wght: 500
    out:
      XTRA: 362.25
      XOPQ: 236
      YOPQ: 236
      SPAC: 20

  # OPSZ = 72

  # Semibold Condensed-MaxOPSZ
  - in:
      opsz: 72
      wdth: 52
      wght: 600
    out:
      XTRA: 354
      XOPQ: 332.733
      YOPQ: 276.933
      SPAC: -20

  # OPSZ = 48

  # Semibold Condensed
  - in:
      opsz: 48
      wdth: 52
      wght: 600
    out:
      XTRA: 354
      XOPQ: 322
      YOPQ: 268
      SPAC: 25

  # OPSZ = 12

  # Semibold Condensed-MinOPSZ
  - in:
      opsz: 12
      wdth: 52
      wght: 600
    out:
      XTRA: 371.7
      XOPQ: 311.267
      YOPQ: 259.067
      SPAC: 20

  # OPSZ = 72

  # Bold Condensed-MaxOPSZ
  - in:
      opsz: 72
      wdth: 52
      wght: 700
    out:
      XTRA: 318
      XOPQ: 427.35
      YOPQ: 364.35
      SPAC: -20

  # OPSZ = 48

  # Bold Condensed
  - in:
      opsz: 48
      wdth: 52
      wght: 700
    out:
      XTRA: 318
      XOPQ: 407
      YOPQ: 347
      SPAC: 25

  # OPSZ = 12

  # Bold Condensed-MinOPSZ
  - in:
      opsz: 12
      wdth: 52
      wght: 700
    out:
      XTRA: 333.9
      XOPQ: 386.65
      YOPQ: 329.65
      SPAC: 20

  # =========================
  # Width = 100
  # =========================

  # OPSZ = 72

  # Thin-MaxOPSZ
  - in:
      opsz: 72
      wdth: 100
      wght: 100
    out:
      XTRA: 461.8
      XOPQ: 44.555
      YOPQ: 41.8
      SPAC: -20

  # OPSZ = 48

  # Thin
  - in:
      opsz: 48
      wdth: 100
      wght: 100
    out:
      XTRA: 461.8
      XOPQ: 46.9
      YOPQ: 44
      SPAC: 25

  # OPSZ = 12

  # Thin-MinOPSZ
  - in:
      opsz: 12
      wdth: 100
      wght: 100
    out:
      XTRA: 461.8
      XOPQ: 49.245
      YOPQ: 46.2
      SPAC: 20

  # OPSZ = 72

  # ExtraLight-MaxOPSZ
  - in:
      opsz: 72
      wdth: 100
      wght: 200
    out:
      XTRA: 580
      XOPQ: 74.646
      YOPQ: 74.66
      SPAC: -20

  # OPSZ = 48

  # ExtraLight
  - in:
      opsz: 48
      wdth: 100
      wght: 200
    out:
      XTRA: 580
      XOPQ: 78.575
      YOPQ: 78.59
      SPAC: 25

  # OPSZ = 12

  # ExtraLight-MinOPSZ
  - in:
      opsz: 12
      wdth: 100
      wght: 200
    out:
      XTRA: 580
      XOPQ: 82.504
      YOPQ: 82.52
      SPAC: 20

  # OPSZ = 72

  # Light-MaxOPSZ
  - in:
      opsz: 72
      wdth: 100
      wght: 300
    out:
      XTRA: 603.55
      XOPQ: 129.796
      YOPQ: 121.147
      SPAC: -20

  # OPSZ = 48

  # Light
  - in:
      opsz: 48
      wdth: 100
      wght: 300
    out:
      XTRA: 603.55
      XOPQ: 133.124
      YOPQ: 124.253
      SPAC: 25

  # OPSZ = 12

  # Light-MinOPSZ
  - in:
      opsz: 12
      wdth: 100
      wght: 300
    out:
      XTRA: 603.55
      XOPQ: 136.452
      YOPQ: 127.359
      SPAC: 20

  # OPSZ = 72

  # Regular-MaxOPSZ
  - in:
      opsz: 72
      wdth: 100
      wght: 400
    out:
      XTRA: 627
      XOPQ: 187.672
      YOPQ: 160
      SPAC: -20

  # OPSZ = 48

  # Regular
  - in:
      opsz: 48
      wdth: 100
      wght: 400
    out:
      XTRA: 627
      XOPQ: 187.672
      YOPQ: 160
      SPAC: 25

  # OPSZ = 12

  # Regular-MinOPSZ
  - in:
      opsz: 12
      wdth: 100
      wght: 400
    out:
      XTRA: 627
      XOPQ: 187.672
      YOPQ: 160
      SPAC: 20

  # OPSZ = 72

  # Medium-MaxOPSZ
  - in:
      opsz: 72
      wdth: 100
      wght: 500
    out:
      XTRA: 650.5
      XOPQ: 246.258
      YOPQ: 219.702
      SPAC: -20

  # OPSZ = 48

  # Medium
  - in:
      opsz: 48
      wdth: 100
      wght: 500
    out:
      XTRA: 650.5
      XOPQ: 242.221
      YOPQ: 216.1
      SPAC: 25

  # OPSZ = 12

  # Medium-MinOPSZ
  - in:
      opsz: 12
      wdth: 100
      wght: 500
    out:
      XTRA: 650.5
      XOPQ: 238.184
      YOPQ: 212.498
      SPAC: 20

  # OPSZ = 72

  # SemiBold-MaxOPSZ
  - in:
      opsz: 72
      wdth: 100
      wght: 600
    out:
      XTRA: 693.05
      XOPQ: 332.196
      YOPQ: 295.533
      SPAC: -20

  # OPSZ = 48

  # SemiBold
  - in:
      opsz: 48
      wdth: 100
      wght: 600
    out:
      XTRA: 693.05
      XOPQ: 321.48
      YOPQ: 286
      SPAC: 25

  # OPSZ = 12

  # SemiBold-MinOPSZ
  - in:
      opsz: 12
      wdth: 100
      wght: 600
    out:
      XTRA: 693.05
      XOPQ: 310.764
      YOPQ: 276.467
      SPAC: 20

  # OPSZ = 72

  # Bold-MaxOPSZ
  - in:
      opsz: 72
      wdth: 100
      wght: 700
    out:
      XTRA: 735.6
      XOPQ: 420.775
      YOPQ: 340.935
      SPAC: -20

  # OPSZ = 48

  # Bold
  - in:
      opsz: 48
      wdth: 100
      wght: 700
    out:
      XTRA: 735.6
      XOPQ: 400.738
      YOPQ: 324.7
      SPAC: 25

  # OPSZ = 12

  # Bold-MinOPSZ
  - in:
      opsz: 12
      wdth: 100
      wght: 700
    out:
      XTRA: 735.6
      XOPQ: 380.701
      YOPQ: 308.465
      SPAC: 20

  # =========================
  # Width = 182
  # =========================

  # OPSZ = 72

  # Thin Extended-MaxOPSZ
  - in:
      opsz: 72
      wdth: 182
      wght: 100
    out:
      XTRA: 1136.3
      XOPQ: 51.87
      YOPQ: 44.935
      SPAC: -20

  # OPSZ = 48

  # Thin Extended
  - in:
      opsz: 48
      wdth: 182
      wght: 100
    out:
      XTRA: 1136.3
      XOPQ: 54.6
      YOPQ: 47.3
      SPAC: 25

  # OPSZ = 12

  # Thin Extended-MinOPSZ
  - in:
      opsz: 12
      wdth: 182
      wght: 100
    out:
      XTRA: 1136.3
      XOPQ: 57.33
      YOPQ: 49.665
      SPAC: 20

  # OPSZ = 72

  # ExtraLight Extended-MaxOPSZ
  - in:
      opsz: 72
      wdth: 182
      wght: 200
    out:
      XTRA: 1259
      XOPQ: 80.75
      YOPQ: 79.8
      SPAC: -20

  # OPSZ = 48

  # ExtraLight Extended
  - in:
      opsz: 48
      wdth: 182
      wght: 200
    out:
      XTRA: 1259
      XOPQ: 85
      YOPQ: 84
      SPAC: 25

  # OPSZ = 12

  # ExtraLight Extended-MinOPSZ
  - in:
      opsz: 12
      wdth: 182
      wght: 200
    out:
      XTRA: 1259
      XOPQ: 89.25
      YOPQ: 88.2
      SPAC: 20

  # OPSZ = 72

  # Light Extended-MaxOPSZ
  - in:
      opsz: 72
      wdth: 182
      wght: 300
    out:
      XTRA: 1259
      XOPQ: 110.175
      YOPQ: 108.225
      SPAC: -20

  # OPSZ = 48

  # Light Extended
  - in:
      opsz: 48
      wdth: 182
      wght: 300
    out:
      XTRA: 1259
      XOPQ: 113
      YOPQ: 111
      SPAC: 25

  # OPSZ = 12

  # Light Extended-MinOPSZ
  - in:
      opsz: 12
      wdth: 182
      wght: 300
    out:
      XTRA: 1259
      XOPQ: 115.825
      YOPQ: 113.775
      SPAC: 20

  # OPSZ = 72

  # Regular Extended-MaxOPSZ
  - in:
      opsz: 72
      wdth: 182
      wght: 400
    out:
      XTRA: 1252.1
      XOPQ: 220.4
      YOPQ: 197.1
      SPAC: -20

  # OPSZ = 48

  # Regular Extended
  - in:
      opsz: 48
      wdth: 182
      wght: 400
    out:
      XTRA: 1252.1
      XOPQ: 220.4
      YOPQ: 197.1
      SPAC: 25

  # OPSZ = 12

  # Regular Extended-MinOPSZ
  - in:
      opsz: 12
      wdth: 182
      wght: 400
    out:
      XTRA: 1252.1
      XOPQ: 220.4
      YOPQ: 197.1
      SPAC: 20

  # OPSZ = 72

  # Medium Extended-MaxOPSZ
  - in:
      opsz: 72
      wdth: 182
      wght: 500
    out:
      XTRA: 1213
      XOPQ: 376.167
      YOPQ: 323.3
      SPAC: -20

  # OPSZ = 48

  # Medium Extended
  - in:
      opsz: 48
      wdth: 182
      wght: 500
    out:
      XTRA: 1213
      XOPQ: 370
      YOPQ: 318
      SPAC: 25

  # OPSZ = 12

  # Medium Extended-MinOPSZ
  - in:
      opsz: 12
      wdth: 182
      wght: 500
    out:
      XTRA: 1213
      XOPQ: 363.833
      YOPQ: 312.7
      SPAC: 20

  # OPSZ = 72

  # Semibold Extended-MaxOPSZ
  - in:
      opsz: 72
      wdth: 182
      wght: 600
    out:
      XTRA: 1275
      XOPQ: 524.933
      YOPQ: 372
      SPAC: -20

  # OPSZ = 48

  # Semibold Extended
  - in:
      opsz: 48
      wdth: 182
      wght: 600
    out:
      XTRA: 1275
      XOPQ: 508
      YOPQ: 360
      SPAC: 25

  # OPSZ = 12

  # Semibold Extended-MinOPSZ
  - in:
      opsz: 12
      wdth: 182
      wght: 600
    out:
      XTRA: 1275
      XOPQ: 491.067
      YOPQ: 348
      SPAC: 20

  # OPSZ = 72

  # Bold Extended-MaxOPSZ
  - in:
      opsz: 72
      wdth: 182
      wght: 700
    out:
      XTRA: 1350
      XOPQ: 608.79
      YOPQ: 410.97
      SPAC: -20

  # OPSZ = 48

  # Bold Extended
  - in:
      opsz: 48
      wdth: 182
      wght: 700
    out:
      XTRA: 1350
      XOPQ: 579.8
      YOPQ: 391.4
      SPAC: 25

  # OPSZ = 12

  # Bold Extended-MinOPSZ
  - in:
      opsz: 12
      wdth: 182
      wght: 700
    out:
      XTRA: 1350
      XOPQ: 550.81
      YOPQ: 371.83
      SPAC: 20

  # =========================
  # Width = 300
  # =========================

  # OPSZ = 72

  # Thin Ultra Extended-MaxOPSZ
  - in:
      opsz: 72
      wdth: 300
      wght: 100
    out:
      XTRA: 2300
      XOPQ: 58.33
      YOPQ: 57.095
      SPAC: -20

  # OPSZ = 48

  # Thin Ultra Extended
  - in:
      opsz: 48
      wdth: 300
      wght: 100
    out:
      XTRA: 2300
      XOPQ: 61.4
      YOPQ: 60.1
      SPAC: 25

  # OPSZ = 12

  # Thin Ultra Extended-MinOPSZ
  - in:
      opsz: 12
      wdth: 300
      wght: 100
    out:
      XTRA: 2300
      XOPQ: 64.47
      YOPQ: 63.105
      SPAC: 20

  # OPSZ = 72

  # ExtraLight Ultra Extended-MaxOPSZ
  - in:
      opsz: 72
      wdth: 300
      wght: 200
    out:
      XTRA: 2300
      XOPQ: 95
      YOPQ: 93.1
      SPAC: -20

  # OPSZ = 48

  # ExtraLight Ultra Extended
  - in:
      opsz: 48
      wdth: 300
      wght: 200
    out:
      XTRA: 2300
      XOPQ: 100
      YOPQ: 98
      SPAC: 25

  # OPSZ = 12

  # ExtraLight Ultra Extended-MinOPSZ
  - in:
      opsz: 12
      wdth: 300
      wght: 200
    out:
      XTRA: 2300
      XOPQ: 105
      YOPQ: 102.9
      SPAC: 20

  # OPSZ = 72

  # Light Ultra Extended-MaxOPSZ
  - in:
      opsz: 72
      wdth: 300
      wght: 300
    out:
      XTRA: 2290
      XOPQ: 130.65
      YOPQ: 124.8
      SPAC: -20

  # OPSZ = 48

  # Light Ultra Extended
  - in:
      opsz: 48
      wdth: 300
      wght: 300
    out:
      XTRA: 2290
      XOPQ: 134
      YOPQ: 128
      SPAC: 25

  # OPSZ = 12

  # Light Ultra Extended-MinOPSZ
  - in:
      opsz: 12
      wdth: 300
      wght: 300
    out:
      XTRA: 2290
      XOPQ: 137.35
      YOPQ: 131.2
      SPAC: 20

  # OPSZ = 72

  # Regular Ultra Extended-MaxOPSZ
  - in:
      opsz: 72
      wdth: 300
      wght: 400
    out:
      XTRA: 2210.6
      XOPQ: 235.2
      YOPQ: 199.5
      SPAC: -20

  # OPSZ = 48

  # Regular Ultra Extended
  - in:
      opsz: 48
      wdth: 300
      wght: 400
    out:
      XTRA: 2210.6
      XOPQ: 235.2
      YOPQ: 199.5
      SPAC: 25

  # OPSZ = 12

  # Regular Ultra Extended-MinOPSZ
  - in:
      opsz: 12
      wdth: 300
      wght: 400
    out:
      XTRA: 2210.6
      XOPQ: 235.2
      YOPQ: 199.5
      SPAC: 20

  # OPSZ = 72

  # Medium Ultra Extended-MaxOPSZ
  - in:
      opsz: 72
      wdth: 300
      wght: 500
    out:
      XTRA: 2290
      XOPQ: 322.283
      YOPQ: 263.317
      SPAC: -20

  # OPSZ = 48

  # Medium Ultra Extended
  - in:
      opsz: 48
      wdth: 300
      wght: 500
    out:
      XTRA: 2290
      XOPQ: 317
      YOPQ: 259
      SPAC: 25

  # OPSZ = 12

  # Medium Ultra Extended-MinOPSZ
  - in:
      opsz: 12
      wdth: 300
      wght: 500
    out:
      XTRA: 2290
      XOPQ: 311.717
      YOPQ: 254.683
      SPAC: 20

  # OPSZ = 72

  # Semibold Ultra Extended-MaxOPSZ
  - in:
      opsz: 72
      wdth: 300
      wght: 600
    out:
      XTRA: 2346
      XOPQ: 481.12
      YOPQ: 370.14
      SPAC: -20

  # OPSZ = 48

  # Semibold Ultra Extended
  - in:
      opsz: 48
      wdth: 300
      wght: 600
    out:
      XTRA: 2346
      XOPQ: 465.6
      YOPQ: 358.2
      SPAC: 25

  # OPSZ = 12

  # Semibold Ultra Extended-MinOPSZ
  - in:
      opsz: 12
      wdth: 300
      wght: 600
    out:
      XTRA: 2346
      XOPQ: 450.08
      YOPQ: 346.26
      SPAC: 20

  # OPSZ = 72

  # Bold Ultra Extended-MaxOPSZ
  - in:
      opsz: 72
      wdth: 300
      wght: 700
    out:
      XTRA: 2369.9
      XOPQ: 670.11
      YOPQ: 406.455
      SPAC: -20

  # OPSZ = 48

  # Bold Ultra Extended
  - in:
      opsz: 48
      wdth: 300
      wght: 700
    out:
      XTRA: 2369.9
      XOPQ: 638.2
      YOPQ: 387.1
      SPAC: 25

  # OPSZ = 12

  # Bold Ultra Extended-MinOPSZ
  - in:
      opsz: 12
      wdth: 300
      wght: 700
    out:
      XTRA: 2369.9
      XOPQ: 606.29
      YOPQ: 367.745
      SPAC: 20

includeSourceFixes: false
