sources:
  - Crispy.glyphs
familyName: Crispy
buildStatic: false

spacingAxis:
  min: 0
  max: 50

fvarInstances:
  Crispy[SPAC,XOPQ,XTRA,YOPQ].ttf:
  - name: ExtraLight
    coordinates:
      wght: 200
      wdth: 100
      opsz: 12
  - name: Light
    coordinates:
      wght: 300
      wdth: 100
      opsz: 12
  - name: Regular
    coordinates:
      wght: 400
      wdth: 100
      opsz: 12
  - name: Medium
    coordinates:
      wght: 500
      wdth: 100
      opsz: 12
  - name: SemiBold
    coordinates:
      wght: 600
      wdth: 100
      opsz: 12
  - name: Bold
    coordinates:
      wght: 700
      wdth: 100
      opsz: 12
  - name: ExtraBold
    coordinates:
      wght: 800
      wdth: 100
      opsz: 12
  - name: Black
    coordinates:
      wght: 900
      wdth: 100
      opsz: 12

avar2:
  Crispy[SPAC,XOPQ,XTRA,YOPQ].ttf:
  - in:
      wght: 200
      wdth: 100
      opsz: 72
    out:
      XTRA: 580
      XOPQ: 72.59
      YOPQ: 78.575
      SPAC: 0
  - in:
      wght: 300
      wdth: 100
      opsz: 72
    out:
      XTRA: 603.55
      XOPQ: 104.253
      YOPQ: 133.124
      SPAC: 0
  - in:
      wght: 400
      wdth: 100
      opsz: 72
    out:
      XTRA: 627
      XOPQ: 135.916
      YOPQ: 187.672
      SPAC: 0
  - in:
      wght: 500
      wdth: 100
      opsz: 72
    out:
      XTRA: 650.5
      XOPQ: 167.58
      YOPQ: 242.221
      SPAC: 0
  - in:
      wght: 600
      wdth: 100
      opsz: 72
    out:
      XTRA: 693.05
      XOPQ: 223.027
      YOPQ: 321.48
      SPAC: 0
  - in:
      wght: 700
      wdth: 100
      opsz: 72
    out:
      XTRA: 735.6
      XOPQ: 278.474
      YOPQ: 400.738
      SPAC: 0
  - in:
      wght: 800
      wdth: 100
      opsz: 72
    out:
      XTRA: 770
      XOPQ: 308.783
      YOPQ: 466.573
      SPAC: 0
  - in:
      wght: 900
      wdth: 100
      opsz: 72
    out:
      XTRA: 804.4
      XOPQ: 339.093
      YOPQ: 532.409
      SPAC: 0

  - in:
      wght: 200
      wdth: 100
      opsz: 12
    out:
      XTRA: 580
      XOPQ: 90.7375
      YOPQ: 88.178594
      SPAC: 50
  - in:
      wght: 300
      wdth: 100
      opsz: 12
    out:
      XTRA: 603.55
      XOPQ: 130.31625
      YOPQ: 149.394681
      SPAC: 50
  - in:
      wght: 400
      wdth: 100
      opsz: 12
    out:
      XTRA: 627
      XOPQ: 169.895
      YOPQ: 210.609647
      SPAC: 50
  - in:
      wght: 500
      wdth: 100
      opsz: 12
    out:
      XTRA: 650.5
      XOPQ: 209.475
      YOPQ: 271.825735
      SPAC: 50
  - in:
      wght: 600
      wdth: 100
      opsz: 12
    out:
      XTRA: 693.05
      XOPQ: 278.78375
      YOPQ: 360.771929
      SPAC: 50
  - in:
      wght: 700
      wdth: 100
      opsz: 12
    out:
      XTRA: 735.6
      XOPQ: 309.10614
      YOPQ: 449.717
      SPAC: 50
  - in:
      wght: 800
      wdth: 100
      opsz: 12
    out:
      XTRA: 770
      XOPQ: 342.74913
      YOPQ: 523.598485
      SPAC: 50
  - in:
      wght: 900
      wdth: 100
      opsz: 12
    out:
      XTRA: 804.4
      XOPQ: 376.39323
      YOPQ: 597.481093
      SPAC: 50


includeSourceFixes: false