sources:
- ../sources/Crispy.glyphs
familyName: Crispy

fvarInstances:
  Crispy[XOPQ,XTRA,YOPQ].ttf:
  - name: Thin
    coordinates:
      opsz: 48
      wdth: 100
      wght: 100
  - name: ExtraLight
    coordinates:
      opsz: 48
      wdth: 100
      wght: 200
  - name: Light
    coordinates:
      opsz: 48
      wdth: 100
      wght: 300
  - name: Regular
    coordinates:
      opsz: 48
      wdth: 100
      wght: 400
  - name: Medium
    coordinates:
      opsz: 48
      wdth: 100
      wght: 500
  - name: SemiBold
    coordinates:
      opsz: 48
      wdth: 100
      wght: 600
  - name: Bold
    coordinates:
      opsz: 48
      wdth: 100
      wght: 700

stat:
  Crispy[XOPQ,XTRA,YOPQ].ttf:
  - name: Optical Size
    tag: opsz
    values:
    - name: 12pt
      value: 12
    - name: 72pt
      value: 72
  - name: Width
    tag: wdth
    values:
    - name: '52'
      value: 52
    - name: Normal
      value: 100
    - name: '182'
      value: 182
    - name: '300'
      value: 300
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 100
    - name: ExtraLight
      value: 200
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700

avar2:
  Crispy[XOPQ,XTRA,YOPQ].ttf:

  # =========================
  # Width = 52
  # =========================

  # OPSZ = 72

  # Thin Condensed
  - in:
      opsz: 72
      wdth: 52
      wght: 100
    out:
      XTRA: 181.2
      XOPQ: 40.3
      YOPQ: 41.3

  # OPSZ = 12

  # Thin Condensed SmallOpsz
  - in:
      opsz: 12
      wdth: 52
      wght: 100
    out:
      XTRA: 194.1
      XOPQ: 60.2
      YOPQ: 40.8

  # OPSZ = 72

  # ExtraLight Condensed
  - in:
      opsz: 72
      wdth: 52
      wght: 200
    out:
      XTRA: 248
      XOPQ: 78
      YOPQ: 85

  # OPSZ = 12

  # ExtraLight Condensed SmallOpsz
  - in:
      opsz: 12
      wdth: 52
      wght: 200
    out:
      XTRA: 326.8
      XOPQ: 78
      YOPQ: 85

  # OPSZ = 72

  # Light Condensed
  - in:
      opsz: 72
      wdth: 52
      wght: 300
    out:
      XTRA: 280
      XOPQ: 95
      YOPQ: 90

  # OPSZ = 12

  # Light Condensed SmallOpsz
  - in:
      opsz: 12
      wdth: 52
      wght: 300
    out:
      XTRA: 368.5
      XOPQ: 95
      YOPQ: 90

  # OPSZ = 72

  # Regular Condensed
  - in:
      opsz: 72
      wdth: 52
      wght: 400
    out:
      XTRA: 290
      XOPQ: 147
      YOPQ: 130

  # OPSZ = 12

  # Regular Condensed SmallOpsz
  - in:
      opsz: 12
      wdth: 52
      wght: 400
    out:
      XTRA: 613.9
      XOPQ: 139.5
      YOPQ: 130

  # OPSZ = 72

  # Medium Condensed
  - in:
      opsz: 72
      wdth: 52
      wght: 500
    out:
      XTRA: 345
      XOPQ: 240
      YOPQ: 240

  # OPSZ = 12

  # Medium Condensed SmallOpsz
  - in:
      opsz: 12
      wdth: 52
      wght: 500
    out:
      XTRA: 642.4
      XOPQ: 266.1
      YOPQ: 240

  # OPSZ = 72

  # Semibold Condensed
  - in:
      opsz: 72
      wdth: 52
      wght: 600
    out:
      XTRA: 354
      XOPQ: 322
      YOPQ: 268

  # OPSZ = 12

  # Semibold Condensed SmallOpsz
  - in:
      opsz: 12
      wdth: 52
      wght: 600
    out:
      XTRA: 544
      XOPQ: 336
      YOPQ: 262.9

  # OPSZ = 72

  # Bold Condensed
  - in:
      opsz: 72
      wdth: 52
      wght: 700
    out:
      XTRA: 318
      XOPQ: 407
      YOPQ: 347

  # OPSZ = 12

  # Bold Condensed SmallOpsz
  - in:
      opsz: 12
      wdth: 52
      wght: 700
    out:
      XTRA: 532.2
      XOPQ: 391
      YOPQ: 335.8

  # =========================
  # Width = 100
  # =========================

  # OPSZ = 72

  # Thin
  - in:
      opsz: 72
      wdth: 100
      wght: 100
    out:
      XTRA: 461.8
      XOPQ: 46.9
      YOPQ: 44

  # OPSZ = 12

  # Thin SmallOpsz
  - in:
      opsz: 12
      wdth: 100
      wght: 100
    out:
      XTRA: 702.6
      XOPQ: 63.1
      YOPQ: 65.9

  # OPSZ = 72

  # ExtraLight
  - in:
      opsz: 72
      wdth: 100
      wght: 200
    out:
      XTRA: 580
      XOPQ: 78.575
      YOPQ: 78.59

  # OPSZ = 12

  # ExtraLight SmallOpsz
  - in:
      opsz: 12
      wdth: 100
      wght: 200
    out:
      XTRA: 741.1
      XOPQ: 87.9
      YOPQ: 78.8

  # OPSZ = 72

  # Light
  - in:
      opsz: 72
      wdth: 100
      wght: 300
    out:
      XTRA: 603.55
      XOPQ: 133.124
      YOPQ: 124.253

  # OPSZ = 12

  # Light SmallOpsz
  - in:
      opsz: 12
      wdth: 100
      wght: 300
    out:
      XTRA: 719.3
      XOPQ: 147.8
      YOPQ: 124.253

  # OPSZ = 72

  # Regular
  - in:
      opsz: 72
      wdth: 100
      wght: 400
    out:
      XTRA: 627
      XOPQ: 187.672
      YOPQ: 160

  # OPSZ = 12

  # Regular SmallOpsz
  - in:
      opsz: 12
      wdth: 100
      wght: 400
    out:
      XTRA: 730.6
      XOPQ: 181
      YOPQ: 160

  # OPSZ = 72

  # Medium
  - in:
      opsz: 72
      wdth: 100
      wght: 500
    out:
      XTRA: 650.5
      XOPQ: 242.221
      YOPQ: 216.1

  # OPSZ = 12

  # Medium SmallOpsz
  - in:
      opsz: 12
      wdth: 100
      wght: 500
    out:
      XTRA: 715.7
      XOPQ: 242.221
      YOPQ: 216.1

  # OPSZ = 72

  # SemiBold
  - in:
      opsz: 72
      wdth: 100
      wght: 600
    out:
      XTRA: 693.05
      XOPQ: 321.48
      YOPQ: 286

  # OPSZ = 12

  # SemiBold SmallOpsz
  - in:
      opsz: 12
      wdth: 100
      wght: 600
    out:
      XTRA: 890.2
      XOPQ: 308
      YOPQ: 277.2

  # OPSZ = 72

  # Bold
  - in:
      opsz: 72
      wdth: 100
      wght: 700
    out:
      XTRA: 735.6
      XOPQ: 400.738
      YOPQ: 324.7

  # OPSZ = 12

  # Bold SmallOpsz
  - in:
      opsz: 12
      wdth: 100
      wght: 700
    out:
      XTRA: 940.8
      XOPQ: 390.9
      YOPQ: 319.4

  # =========================
  # Width = 182
  # =========================

  # OPSZ = 72

  # Thin Extended
  - in:
      opsz: 72
      wdth: 182
      wght: 100
    out:
      XTRA: 1136.3
      XOPQ: 54.6
      YOPQ: 47.3

  # OPSZ = 12

  # Thin Extended SmallOpsz
  - in:
      opsz: 12
      wdth: 182
      wght: 100
    out:
      XTRA: 1718.6
      XOPQ: 106.1
      YOPQ: 70.9

  # OPSZ = 72

  # ExtraLight Extended
  - in:
      opsz: 72
      wdth: 182
      wght: 200
    out:
      XTRA: 1259
      XOPQ: 85
      YOPQ: 84

  # OPSZ = 12

  # ExtraLight Extended SmallOpsz
  - in:
      opsz: 12
      wdth: 182
      wght: 200
    out:
      XTRA: 1473.2
      XOPQ: 98.2
      YOPQ: 88.1

  # OPSZ = 72

  # Light Extended
  - in:
      opsz: 72
      wdth: 182
      wght: 300
    out:
      XTRA: 1259
      XOPQ: 113
      YOPQ: 111

  # OPSZ = 12

  # Light Extended SmallOpsz
  - in:
      opsz: 12
      wdth: 182
      wght: 300
    out:
      XTRA: 1498.7
      XOPQ: 113
      YOPQ: 111

  # OPSZ = 72

  # Regular Extended
  - in:
      opsz: 72
      wdth: 182
      wght: 400
    out:
      XTRA: 1252.1
      XOPQ: 220.4
      YOPQ: 197.1

  # OPSZ = 12

  # Regular Extended SmallOpsz
  - in:
      opsz: 12
      wdth: 182
      wght: 400
    out:
      XTRA: 1542.2
      XOPQ: 220.4
      YOPQ: 197.1

  # OPSZ = 72

  # Medium Extended
  - in:
      opsz: 72
      wdth: 182
      wght: 500
    out:
      XTRA: 1213
      XOPQ: 370
      YOPQ: 318

  # OPSZ = 12

  # Medium Extended SmallOpsz
  - in:
      opsz: 12
      wdth: 182
      wght: 500
    out:
      XTRA: 1480.6
      XOPQ: 375.4
      YOPQ: 301.7

  # OPSZ = 72

  # Semibold Extended
  - in:
      opsz: 72
      wdth: 182
      wght: 600
    out:
      XTRA: 1275
      XOPQ: 508
      YOPQ: 360

  # OPSZ = 12

  # Semibold Extended SmallOpsz
  - in:
      opsz: 12
      wdth: 182
      wght: 600
    out:
      XTRA: 1535.5
      XOPQ: 508
      YOPQ: 360

  # OPSZ = 72

  # Bold Extended
  - in:
      opsz: 72
      wdth: 182
      wght: 700
    out:
      XTRA: 1350
      XOPQ: 579.8
      YOPQ: 391.4

  # OPSZ = 12

  # Bold Extended SmallOpsz
  - in:
      opsz: 12
      wdth: 182
      wght: 700
    out:
      XTRA: 1642.9
      XOPQ: 579.8
      YOPQ: 391.4

  # =========================
  # Width = 300
  # =========================

  # OPSZ = 72

  # Thin Ultra Extended
  - in:
      opsz: 72
      wdth: 300
      wght: 100
    out:
      XTRA: 2300
      XOPQ: 61.4
      YOPQ: 60.1

  # OPSZ = 12

  # Thin Ultra Extended SmallOpsz
  - in:
      opsz: 12
      wdth: 300
      wght: 100
    out:
      XTRA: 2654.2
      XOPQ: 79.7
      YOPQ: 69.5

  # OPSZ = 72

  # ExtraLight Ultra Extended
  - in:
      opsz: 72
      wdth: 300
      wght: 200
    out:
      XTRA: 2300
      XOPQ: 100
      YOPQ: 98

  # OPSZ = 12

  # ExtraLight Ultra Extended SmallOpsz
  - in:
      opsz: 12
      wdth: 300
      wght: 200
    out:
      XTRA: 2534.2
      XOPQ: 115.1
      YOPQ: 101

  # OPSZ = 72

  # Light Ultra Extended
  - in:
      opsz: 72
      wdth: 300
      wght: 300
    out:
      XTRA: 2290
      XOPQ: 134
      YOPQ: 128

  # OPSZ = 12

  # Light Ultra Extended SmallOpsz
  - in:
      opsz: 12
      wdth: 300
      wght: 300
    out:
      XTRA: 2679.6
      XOPQ: 134
      YOPQ: 128

  # OPSZ = 72

  # Regular Ultra Extended
  - in:
      opsz: 72
      wdth: 300
      wght: 400
    out:
      XTRA: 2210.6
      XOPQ: 235.2
      YOPQ: 199.5

  # OPSZ = 12

  # Regular Ultra Extended SmallOpsz
  - in:
      opsz: 12
      wdth: 300
      wght: 400
    out:
      XTRA: 2528.2
      XOPQ: 244.9
      YOPQ: 199.5

  # OPSZ = 72

  # Medium Ultra Extended
  - in:
      opsz: 72
      wdth: 300
      wght: 500
    out:
      XTRA: 2290
      XOPQ: 317
      YOPQ: 259

  # OPSZ = 12

  # Medium Ultra Extended SmallOpsz
  - in:
      opsz: 12
      wdth: 300
      wght: 500
    out:
      XTRA: 2502.3
      XOPQ: 323.2
      YOPQ: 273.5

  # OPSZ = 72

  # Semibold Ultra Extended
  - in:
      opsz: 72
      wdth: 300
      wght: 600
    out:
      XTRA: 2346
      XOPQ: 465.6
      YOPQ: 358.2

  # OPSZ = 12

  # Semibold Ultra Extended SmallOpsz
  - in:
      opsz: 12
      wdth: 300
      wght: 600
    out:
      XTRA: 2744.3
      XOPQ: 465.6
      YOPQ: 358.2

  # OPSZ = 72

  # Bold Ultra Extended
  - in:
      opsz: 72
      wdth: 300
      wght: 700
    out:
      XTRA: 2369.9
      XOPQ: 619.7
      YOPQ: 362

  # OPSZ = 12

  # Bold Ultra Extended SmallOpsz
  - in:
      opsz: 12
      wdth: 300
      wght: 700
    out:
      XTRA: 2738.5
      XOPQ: 619.7
      YOPQ: 331.9
